"""Deterministic, fail-closed supervised action safety core."""

from .executor import ActionTransaction, ExecutionResult, SafeActionExecutor
from .freshness import ocr_reuse_denial, roi_hash_map, sha256_bytes
from .models import (
    CAPABILITY_ALREADY_CONSUMED,
    CAPABILITY_ACTION_KEY_MISMATCH,
    CAPABILITY_ACTION_CLASS_MISMATCH,
    CAPABILITY_ACTION_MISMATCH,
    CAPABILITY_AUTHORIZED,
    CAPABILITY_CAPTURE_MISMATCH,
    CAPABILITY_COORDINATE_MISMATCH,
    CAPABILITY_DIGEST_ONLY_REJECTED,
    CAPABILITY_DRY_RUN_ZERO_TRANSPORT,
    CAPABILITY_FORGERY,
    CAPABILITY_GEOMETRY_MISMATCH,
    CAPABILITY_NAVIGATION_CONSEQUENTIAL_DENIED,
    CAPABILITY_PROFILE_MISMATCH,
    CAPABILITY_PRE_DISPATCH_PHASE_REQUIRED,
    CAPABILITY_RETIRED_NO_DISPATCH,
    CAPABILITY_SCHEMA_INVALID,
    CAPABILITY_SEMANTIC_ACTION_MISMATCH,
    CAPABILITY_SESSION_MISMATCH,
    CAPABILITY_STALE_OBSERVATION,
    CAPABILITY_TIMING_INVALID,
    CAPABILITY_TARGET_MISMATCH,
    CAPABILITY_TASK_MISMATCH,
    CAPABILITY_UNKNOWN_CLASS_DENIED,
    ActionClass,
    ActionIntent,
    ActionStatus,
    CapabilityAuditRecord,
    CapabilityAuthorityBinding,
    CapabilityConsumeResult,
    CapabilityIssueResult,
    InputCapability,
    Observation,
    PolicyDecision,
    PolicyRequest,
    PolicyResult,
    TransportResult,
)
from .policy import CentralPolicy
from .promotional import (
    MAX_PROMOTIONAL_BACKS,
    PromotionalBackSequence,
    PromotionalSequenceError,
)
from .store import CURRENT_SCHEMA_VERSION, SafetyStore
from .task_state import SQLiteTaskStateRepository
from .scheduler_invocation_state import SQLiteSchedulerInvocationRepository
from .popup import (
    ALLIANCE_FORT_WAVE_ALERT,
    UPDATE_RESTART_ALERT,
    PopupController,
    PopupObservation,
    alliance_fort_dismissal_allowed,
    classify_popup_semantics,
    popup_dismissal_verified,
)

__all__ = [
    "ActionClass",
    "ALLIANCE_FORT_WAVE_ALERT",
    "ActionTransaction",
    "ActionIntent",
    "ActionStatus",
    "CAPABILITY_ALREADY_CONSUMED",
    "CAPABILITY_ACTION_KEY_MISMATCH",
    "CAPABILITY_ACTION_CLASS_MISMATCH",
    "CAPABILITY_ACTION_MISMATCH",
    "CAPABILITY_AUTHORIZED",
    "CAPABILITY_CAPTURE_MISMATCH",
    "CAPABILITY_COORDINATE_MISMATCH",
    "CAPABILITY_DIGEST_ONLY_REJECTED",
    "CAPABILITY_DRY_RUN_ZERO_TRANSPORT",
    "CAPABILITY_FORGERY",
    "CAPABILITY_GEOMETRY_MISMATCH",
    "CAPABILITY_NAVIGATION_CONSEQUENTIAL_DENIED",
    "CAPABILITY_PROFILE_MISMATCH",
    "CAPABILITY_PRE_DISPATCH_PHASE_REQUIRED",
    "CAPABILITY_RETIRED_NO_DISPATCH",
    "CAPABILITY_SCHEMA_INVALID",
    "CAPABILITY_SEMANTIC_ACTION_MISMATCH",
    "CAPABILITY_SESSION_MISMATCH",
    "CAPABILITY_STALE_OBSERVATION",
    "CAPABILITY_TIMING_INVALID",
    "CAPABILITY_TARGET_MISMATCH",
    "CAPABILITY_TASK_MISMATCH",
    "CAPABILITY_UNKNOWN_CLASS_DENIED",
    "CapabilityAuditRecord",
    "CapabilityAuthorityBinding",
    "CapabilityConsumeResult",
    "CapabilityIssueResult",
    "CentralPolicy",
    "InputCapability",
    "MAX_PROMOTIONAL_BACKS",
    "CURRENT_SCHEMA_VERSION",
    "ExecutionResult",
    "Observation",
    "PolicyDecision",
    "PolicyRequest",
    "PolicyResult",
    "PromotionalBackSequence",
    "PromotionalSequenceError",
    "PopupController",
    "PopupObservation",
    "SafeActionExecutor",
    "SafetyStore",
    "SQLiteTaskStateRepository",
    "SQLiteSchedulerInvocationRepository",
    "TransportResult",
    "UPDATE_RESTART_ALERT",
    "alliance_fort_dismissal_allowed",
    "classify_popup_semantics",
    "ocr_reuse_denial",
    "popup_dismissal_verified",
    "roi_hash_map",
    "sha256_bytes",
]
